spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pizzaria_dev
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    com.br.pizzaria: DEBUG
    org.springframework.kafka: INFO
